name: CI

on:

  push:
    branches:
      - main
      - dev
      - Dev
      - '*'

  pull_request:
    branches:
      - main
      - dev
      - Dev

jobs:

  # Test job
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12"]
        poetry-version: ["1.7.0"]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: poetry Install
        run: poetry install --only test

      # - name: Run Pytest
      #   run: poetry run pytest

      # - name : coverage
      #   run: poetry run pytest --cov=app --cov-report=xml

  # Code quality job
  code-quality:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12"]
        poetry-version: ["1.7.0"]

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: poetry Install
        run: poetry install --only qa

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run bandit
        run: poetry run bandit .

      - name: Run safety
        run: poetry run safety check

      - name: Run black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check-only --profile black
